### ISSUE TITLE
Include it into Reactos

### ISSUE THREAD

**Issue by blackcrack** [mity/c-win32#1]
Hi,

i have not your mailadress, so try i am on this way..

lil' question, why do you not help programming at reactos.org,
They are have done many in the last years.
Reactos.org is an Independence WinNT programming under GPL2.
Reactos.org works together with Wine for Linux as WinNTSubsystem
Reactos is download and use for free. At Moment have MS Win from Redmond a Wold wide Cartel, bad Politike ad this not only in Price , work together with Facility's from the States and is closed source, nobody can see what is in the kernel and more deep, because parts of code be still not viewable.
If i look on the german Munich, have this also a problematic... (Linux, back to MS and so on), so can we speak also from a "Munichproblematic".. You have enough know hoff about the code and programming like i have can see on you Webpage and here in github, where you could help with as a good Programmer for bring Reactos.org to finishing for using for all and support the whole world to be in depended in WinNT like with Linux and the power take out of the hand from the Factory from Redmond to have a Independence WinNT, Programmed from the Community for the community if the Internet and you be one of them.
And, all What you programming in Reactos is not lost for the Future, you help to build up a Open Source and therewith a honest System more honest as can them Commerce WinNT from Redmond, because all real open and viewable and exist in the future also forth.. all what you bring directly in, stay in the future further. so, come and help Reactos, help your self with a Open Source GPL2 'ed and the whole Internet Community.
Call Friends in IRC, speak with other Programmers from your Land, or Peoples in your closer to the vicinity.

Reactos is important, Reactos as Opensource and Free WinNT System does matter .. 
Come and help.

chat.reactos.org
the best Contacts be 
Zero3K (from reboot.pro)
hbelusca ( Hermès BÉLUSCA - MAÏTO )

best regards
Blacky

**Comment by mity** [comment]
No one prevents to use the code in Reactos if they find it useful. The MIT license certainly allows that. 

That said, I very much doubt it would help them because the purpose of the "project" is to make possible to build some C (not C++) projects build in MSVC. It was not created to save the world from a bad evil in Redmond as you likely see it. It's here only because I needed it for my projects. It's published here because maybe other people may find it useful. Nothing more and nothing less.

AFAIK, headers from mingw-w64 and Wine likely do not share the same problems described in the README.md. So, if a project restricts itself to mingw-w64, it does not need any hacky solution similar to the one offered here. 

I don't know enough about Reactos but I believe using the headers from mingw-w64 or wine (those two btw collaborate on them) would help them much more. And it's quite possible that Reactos already does that as it...

> why do you not help programming at reactos.org,

I hope we can agree that I am free to dedicate my limited time to hobby projects of my own choice.

**Comment by blackcrack** [comment]
@mity, well, you could maybe help, you could take a look on Reactos.org
You are very welcome  .. 

best regards
Blacky
